version: '2'

services:
  product-service:
    build: QUOI
    volumes:
      - QUOI:VERS?
    ports:
      - XXXX:XX
  website:
    image: IMAGE
    volumes: 
      - .QUOI:VERS?
    ports:
      - XXXXX:XX
    depends_on:
      - XXXXXXXXXXXXXXXXX
